const Payment = require('../models/payment');
const Sales = require('../models/sales');
const PDFDocument = require('pdfkit');

const createPayment = async (req, res) => {
  try {
    const { saleId, amount, paymentMethod, status, notes } = req.body;

    if (!saleId || !amount) {
      return res.status(400).json({
        message: 'Sale and amount are required'
      });
    }

    const sale = await Sales.findById(req.body.saleId);

    if (!sale) {
      return res.status(404).json({
        message: 'Sale not found'
      });
    }

    const payment = await Payment.create({
      saleId,
      customerId: sale.customerId,
      amount,
      paymentMethod,
      status,
      notes,
      paidBy: req.user.userId
    });

    res.status(201).json({
      message: 'Payment created successfully',
      payment
    });
  } catch (error) {
    res.status(500).json({
      message: error.message
    });
  }
};

const getPayments = async (req, res) => {
  try {
    const payments = await Payment.find()
      .populate('saleId', 'totalAmount quantity')
      .populate('customerId', 'name phone')
      .populate('paidBy', 'name role')
      .sort({ createdAt: -1 });

    res.status(200).json({
      message: 'Payments fetched successfully',
      payments
    });
  } catch (error) {
    res.status(500).json({
      message: error.message
    });
  }
};

const generateInvoicePDF = async (req, res) => {
  try {
    const { paymentId } = req.params;
    
    const payment = await Payment.findById(paymentId)
      .populate('customerId', 'name email phone address')
      .populate('saleId', 'totalAmount quantity bikeId')
      .populate('paidBy', 'name role');
    
    if (!payment) {
      return res.status(404).json({ message: 'Payment not found' });
    }
    
    // Create PDF document
    const doc = new PDFDocument({ margin: 50 });
    
    // Set response headers for PDF download
    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', `attachment; filename=invoice-${paymentId}.pdf`);
    
    // Pipe PDF to response
    doc.pipe(res);
    
    // Header
    doc.fontSize(24).fillColor('#333333').text('BIKE CRM INVOICE', 50, 50);
    doc.fontSize(12).fillColor('#666666').text(`Invoice ID: INV-${payment._id.toString().slice(-8).toUpperCase()}`, 50, 85);
    doc.text(`Date: ${payment.createdAt.toDateString()}`, 50, 100);
    
    // Invoice details box
    doc.rect(50, 120, 500, 80).stroke();
    doc.fontSize(14).fillColor('#333333').text('INVOICE DETAILS', 60, 135);
    doc.fontSize(11).fillColor('#555555')
       .text(`Customer: ${payment.customerId.name}`, 60, 155)
       .text(`Email: ${payment.customerId.email || 'N/A'}`, 60, 170)
       .text(`Phone: ${payment.customerId.phone || 'N/A'}`, 60, 185);
    
    // Payment details
    doc.fontSize(14).fillColor('#333333').text('PAYMENT DETAILS', 50, 230);
    
    // Table headers
    const tableTop = 260;
    doc.fontSize(12).fillColor('#333333');
    doc.text('Description', 50, tableTop);
    doc.text('Payment Method', 200, tableTop);  
    doc.text('Amount', 350, tableTop);
    doc.text('Status', 450, tableTop);
    
    // Table line
    doc.moveTo(50, tableTop + 20).lineTo(550, tableTop + 20).stroke();
    
    // Table data
    doc.fontSize(11).fillColor('#555555');
    doc.text('Bike Purchase Payment', 50, tableTop + 30);
    doc.text(payment.paymentMethod.toUpperCase(), 200, tableTop + 30);
    doc.text(`₹${payment.amount.toLocaleString('en-IN')}`, 350, tableTop + 30);
    doc.text(payment.status.toUpperCase(), 450, tableTop + 30);
    
    // Total section
    doc.moveTo(50, tableTop + 60).lineTo(550, tableTop + 60).stroke();
    doc.fontSize(14).fillColor('#333333').text('TOTAL AMOUNT:', 350, tableTop + 80);
    doc.fontSize(16).fillColor('#2563eb').text(`₹${payment.amount.toLocaleString('en-IN')}`, 450, tableTop + 80);
    
    // Payment status
    const statusColor = payment.status === 'paid' ? '#10b981' : 
                       payment.status === 'pending' ? '#f59e0b' : '#ef4444';
    doc.fontSize(12).fillColor(statusColor).text(`Payment Status: ${payment.status.toUpperCase()}`, 50, tableTop + 110);
    
    // Footer
    doc.fontSize(10).fillColor('#888888')
       .text('Generated by Bike CRM System', 50, 700)
       .text(`Generated on: ${new Date().toLocaleString('en-IN')}`, 50, 715)
       .text(`Processed by: ${payment.paidBy?.name || 'System'}`, 50, 730);
    
    // Finalize PDF
    doc.end();
    
  } catch (error) {
    res.status(500).json({ message: 'Error generating PDF', error: error.message });
  }
};

module.exports = {
  createPayment,
  getPayments,  
  generateInvoicePDF
};